### ISSUE TITLE
It doesn't clear marketplace raw code cache

### ISSUE THREAD

**Issue by Tetrax-10** [kyrie25/Spicetify-Cache-Cleaner#2]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.92.647.ga4397eb7
- Spicetify version: 2.12.0
windows 11
```

### 📝 Description

[Tominator said](https://discord.com/channels/842219447716151306/916348019560042526/1011909121324355654) marketplace uses a third party module to dump raw code as cache. So if an extension got a new commit it takes 15-24 hrs to reflect in marketplace. So I uninstalled [Sort By Play Count extension](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Sort-by-Play-count) and cleared the cache manually using this extension and installed my extension again to see whether the [new commit](https://github.com/Tetrax-10/Spicetify-Extensions/commit/44c58f4f9a33c67dfd950a35da47b6423014989f) is reflected in marketplace. But still cant see the new commit in marketplace only the cached code is being installed.

**Comment by kyrie25** [comment]
Client's cache is different from Spotify's player cache, the same logic is applied on browsers.
If you wish to dump cache that the Spotify **client** manages then look up how to clear Chromium browser cache. `Cache Cleaner` clears what Spotify's internal functions manages.
